kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    labels:
      tier: principal
  - role: worker
    labels:
      tier: trabalhador-1
  - role: worker
    labels:
      tier: trabalhador-2
    
  - role: 
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        protocol: TCP
      - containerPort: 30003
        hostPort: 443
        protocol: TCP